name: 'Vagrantup using VirtualBox'
description: 'Run CI in VirtualBox for GitHub Actions'
inputs:
  box:
    description: 'the vagrant box name'
    required: true
  run:
    description: 'the commands to run in vm'
    required: true
  mem:
    description: 'the memory size of the vm'
    required: false
    default: '8192'
branding:
  icon: 'activity'
  color: 'green'

runs:
  using: 'composite'
  steps:
  - name: Detect Runner OS
    if: runner.os != 'macOS'
    run: |
      echo "Vagrant is supported only on macos-12"
      exit 1
    shell: bash

  - name: Get system info
    uses: kenchan0130/actions-system-info@master
    id: system-info

  - name: Get system info through other ways
    uses: sersoft-gmbh/os-version-action@v3
    id: os-version

  - name: Detect Runner OS Release Version
    run: |
      #if [[ ${{ steps.system-info.outputs.release }} != "12" ]]; then
      if [[ ${{ steps.os-version.outputs.version }} != "12" ]]; then
        echo "Vagrant is supported only on macos-12"
        exit 1
      fi
    shell: bash

  - name: Reformat box name for caching
    id: vars
    run: |
      FULLDISTRO=${{ inputs.box }}
      echo "{distro_name}={${FULLDISTRO////_}}" >> $GITHUB_OUTPUT

    shell: bash

  - name: Cache Vagrant boxes
    uses: actions/cache@v4
    with:
      path: ~/.vagrant.d/boxes
      key: ${{ runner.os }}-vagrant-${{ steps.vars.outputs.distro_name }}
      restore-keys: |
        ${{ runner.os }}-vagrant-${{ steps.vars.outputs.distro_name }}

  - name: Vagrant Up the box
    run: |
      run() {
        printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
        eval "$*"
      }

      WORK_DIR=$(mktemp -d)

      run cd "$WORK_DIR"

      run vagrant init ${{inputs.box}}

      echo 'set -e' > shell.sh
      export -p | grep 'GITHUB_' >> shell.sh
      echo "cd /home/vagrant/${GITHUB_REPOSITORY}" >> shell.sh
      cat >> shell.sh <<'EOF'
      run() {
        printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
        eval "$*"
      }

      ${{inputs.run}}
      EOF

      cat > Vagrantfile <<EOF
        Vagrant.configure("2") do |config|
          config.vm.box = "${{inputs.box}}"
          config.vm.provider "virtualbox" do |vb|
            vb.memory = "${{inputs.mem}}"
          end
          config.vm.synced_folder "${GITHUB_WORKSPACE}", "/home/vagrant/${GITHUB_REPOSITORY}", SharedFoldersEnableSymlinksCreate: false
          config.vm.provision "shell", path: "shell.sh"
        end
      EOF

      run cat Vagrantfile
      run cat shell.sh

      run vagrant up --provision
    shell: bash
